services:
  localstack:
    image: localstack/localstack:3
    container_name: torneio-sinuca-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: dynamodb,s3
      DEFAULT_REGION: sa-east-1
      DEBUG: "0"
      PERSISTENCE: "1"
      SNAPSHOT_SAVE_STRATEGY: ON_REQUEST
      SNAPSHOT_LOAD_STRATEGY: ON_STARTUP
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
